### ISSUE TITLE
Extend EquipmentProperties to be suitable for ramp information

### ISSUE THREAD

**Issue by k00ni** [sozialhelden/ac-format#10]
I would like to add the following properties to `EquipmentProperties` in order to support more information about ramps.

| Property                 | Type    |
|:-------------------------|:--------|
| rampLength               | Length   |
| rampWidth                | Length   |
| rampHeight               | Length    |
| rampAngle (*rampGradient*) **?**                | float    |
| hasHandrailLeft          | boolean |
| hasHandrailRight         | boolean |
| rampStartAndEndColorized | boolean |

I've chose the `ramp` suffix to be in line with properties like `cabinLength` and `cabinWidth`.

Using `hasHandRail` is not enough, because sometimes you only have a handrail on one side. For my case i would prefer information if there is one on each side, or not.

**EDIT**: Adapted the Type for ramp* properties.

**Comment by opyh** [comment]
The problem with 'left' and 'right' is that it's not really clear from where you look :) I'd rather keep it simple. For ramps, it's a bit more difficult: They can be different in different levels of elevators, for example, and I haven't seen data like this in the real world yet. Have you? I'd rather suggest to include this information in the way relations to the elevator, or have a `Ramp` entity to allow attaching multiple ramps to multiple elevator doors at some point.

**Comment by k00ni** [comment]
> The problem with 'left' and 'right' is that it's not really clear from where you look :)

Fair point.

> [...] and I haven't seen data like this in the real world yet. Have you?

Yes. I am working with the Behindertenverband Leipzig e.V. since 2015 to release their database as Open Data, for instance. The database is maintained since 1997 and contains information about ~1800 buildings/places in Leipzig and their degree of accessibility. There are over 75 data fields, which describe relevant aspects of a place, for instance entrance, elevator, toilet and supports for visually and hearing impaired people.

In this database you will find exactly these information i was referring to. Its in German and called "Rampe-Handlauf-durchgehend-links-vorhanden" for instance, which translates roughly to "ramp-handrail-left-available".

Our working repository is https://github.com/AKSW/transform-bvl-pages-to-csv-file

You find an old version of the raw data here: https://github.com/AKSW/transform-bvl-pages-to-csv-file/blob/master/places.csv (here is an [RDF](https://github.com/AKSW/transform-bvl-pages-to-csv-file/blob/master/places.n3) version).

German HTML version of the (old, but maintained) data: http://www.le-online.de/inhalt.htm

**Comment by opyh** [comment]
Thanks for this info! Then let's add these attributes and clarify in their documentation what 'left' and 'right' means.

**Comment by k00ni** [comment]
### Regarding "rampAngle"

I would use "rampGradient" instead, because it seems the best translation for "Steigung der Rampe" ([source](https://www.linguee.com/english-german/search?source=auto&query=steigung+der+rampe)).

What measure/attribute is to use here? My data is currently modeled using percent, like 6%. @opyh I know we may discussed this yesterday, but i couldn't remember, if we came to a decision here.

What do you think?

**Comment by k00ni** [comment]
Further discussions in #14.
