### ISSUE TITLE
How do you identify a place on a global scale?

### ISSUE THREAD

**Issue by k00ni** [sozialhelden/ac-format#12]
I would like to know how you identify a place in a unique way? For instance, by a given ID string.

If i understand a11y right, there is the [ids](https://sozialhelden.github.io/ac-format/interfaces/placeproperties.html#ids) property for `PlaceProperties`, which contains [ExternalId](https://github.com/sozialhelden/ac-format/blob/66bde6d/src/ExternalId.ts#L6) references. But its not meant to be used to identify a place, like a certain supermarket located under a given address, am i right? Its current use is not clear to me.

In the RDF/Linked Open Data space we use an [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) / [IRI](https://de.wikipedia.org/wiki/Internationalized_Resource_Identifier) to identify resources on a global scale. A simple example: `http://my_website/supermarketXY`

**Would be open to extend `PlaceInfo` (or `PlaceProperties`) by an `identifier` property, which contains an URI or IRI?**

**Comment by mutaphysis** [comment]
Any ExternalId can of course contain an uri and is meant exactly for your purpose. 

The same place might be backed by different services, and each provider has different ways of referencing them. E.g. HERE and Google have the concept of a placeId, https://developer.here.com/documentation/places/topics_api/media-type-place.html#media-type-place__base / https://developers.google.com/places/place-id .

An uri would of course already contain the provider, but for ease of use repeating the base url of the the places uri will not hurt.

**Comment by k00ni** [comment]
Ah OK, thank you for the fast clarification. 

The only source about ExternalId i could find is [here](https://github.com/sozialhelden/ac-format/blob/66bde6d/src/ExternalId.ts#L7). But the description is misleading IMHO.

For `ExternalId.provider`:
> Organization who manages the equipment database, or name of the ID standard.

Equipment database and ID standard pushed me off the cliff.

**Comment by k00ni** [comment]
I am currently creating a database model using Doctrine to make use of a11y. The fact that the ID of a place is located in a sub-sub-entity is very unfortunate. 

Usually fetching an object from the database only requires to know a certain property-value pair, for instance `id = X`. But in a11y i have:

```
PlaceInfo.properties ==> PlaceProperties.ids => ExternalId.id = X
```
So i would need a JOIN of 3 tables to get the related `PlaceInfo` instance for a given `X`. IMHO that is overkill. 

What do you think about adding an `id` property to `PlaceInfo`? It could be duplicated in an referenced `ExternalId` instance, if necessary. This way you can common ways to access your places, but be compatible to the spec.

**Comment by opyh** [comment]
It would be totally okay to add an _id field at the top level of PlaceInfo and EquipmentInfo – actually that's what we do on accessibility.cloud right now, it's just not part of the specs yet.
