### ISSUE TITLE
What is the meaning of these -Info and -Properties classes/entities?

### ISSUE THREAD

**Issue by k00ni** [sozialhelden/ac-format#8]
Why are properties of a Place attached to `PlaceProperties` instead of `PlaceInfo`? Same goes for `EquipmentInfo` and `EquipmentProperties`. 

But why not for `Entrance`? All properties are directly attached to it, no "proxy" entity.

**Comment by opyh** [comment]
Thanks for this input!

`PlaceInfo` and `EquipmentInfo` are GeoJSON `Feature` compatible main entities to display on maps.

Using this format allows users to use the data much easier with existing GIS tools and libraries. 

Separating geometry and accessibility properties also allows to later attach accessibility properties to more complicated geometry data, like 3D ways/relations that can be found in building information management data formats like [IMDF](https://register.apple.com/resources/imdf/).

I like your idea to make this more consistent, e.g. to get rid of the `Info` suffix we have for legacy reasons, and to have a `Properties` suffix for everything that would usually go in a `properties` field in a GeoJSON feature. As we have an existing code base to manage together with these breaking changes, it might take a while to get there, but let's see how we can make this happen!

**Comment by k00ni** [comment]
> I like your idea to make this more consistent, e.g. to get rid of the Info suffix we have for legacy reasons, and to have a Properties suffix for everything that would usually go in a properties field in a GeoJSON feature. As we have an existing code base to manage together with these breaking changes, it might take a while to get there, but let's see how we can make this happen!

Getting rid of suffixes wasn't my intention :) Your explanation makes sense and i totally support this approach of splitting accessibility and geometry properties. My problem was, that i could not see this and therefore was wondering about the inconsistency, like for `Entrance`. My suggestion would be to align all entities to use the same approach.

**Comment by k00ni** [comment]
For me the issue is clarified, so we can close this.

Or do you want to keep it open as a place of discussion?

> I like your idea to make this more consistent, e.g. to get rid of the Info suffix we have for legacy reasons, and to have a Properties suffix for everything that would usually go in a properties field in a GeoJSON feature. As we have an existing code base to manage together with these breaking changes, it might take a while to get there, but let's see how we can make this happen!
